// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: gateway/v1/gateway.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on IdempotentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *IdempotentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IdempotentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IdempotentResponseMultiError, or nil if none found.
func (m *IdempotentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *IdempotentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	if len(errors) > 0 {
		return IdempotentResponseMultiError(errors)
	}

	return nil
}

// IdempotentResponseMultiError is an error wrapping multiple validation errors
// returned by IdempotentResponse.ValidateAll() if the designated constraints
// aren't met.
type IdempotentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IdempotentResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IdempotentResponseMultiError) AllErrors() []error { return m }

// IdempotentResponseValidationError is the validation error returned by
// IdempotentResponse.Validate if the designated constraints aren't met.
type IdempotentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IdempotentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IdempotentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IdempotentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IdempotentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IdempotentResponseValidationError) ErrorName() string {
	return "IdempotentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e IdempotentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIdempotentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IdempotentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IdempotentResponseValidationError{}

// Validate checks the field values on GetVersionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetVersionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetVersionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetVersionResponseMultiError, or nil if none found.
func (m *GetVersionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetVersionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GitVersion

	// no validation rules for GitCommit

	// no validation rules for GitTreeState

	// no validation rules for BuildDate

	// no validation rules for GoVersion

	// no validation rules for Compiler

	// no validation rules for Platform

	if len(errors) > 0 {
		return GetVersionResponseMultiError(errors)
	}

	return nil
}

// GetVersionResponseMultiError is an error wrapping multiple validation errors
// returned by GetVersionResponse.ValidateAll() if the designated constraints
// aren't met.
type GetVersionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetVersionResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetVersionResponseMultiError) AllErrors() []error { return m }

// GetVersionResponseValidationError is the validation error returned by
// GetVersionResponse.Validate if the designated constraints aren't met.
type GetVersionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetVersionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetVersionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetVersionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetVersionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetVersionResponseValidationError) ErrorName() string {
	return "GetVersionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetVersionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetVersionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetVersionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetVersionResponseValidationError{}

// Validate checks the field values on MinerSet with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MinerSet) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MinerSet with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MinerSetMultiError, or nil
// if none found.
func (m *MinerSet) ValidateAll() error {
	return m.validate(true)
}

func (m *MinerSet) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Replicas

	// no validation rules for DisplayName

	// no validation rules for DeletePolicy

	if all {
		switch v := interface{}(m.GetMinerTemplate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MinerSetValidationError{
					field:  "MinerTemplate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MinerSetValidationError{
					field:  "MinerTemplate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMinerTemplate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MinerSetValidationError{
				field:  "MinerTemplate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MinerSetValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MinerSetValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MinerSetValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MinerSetValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MinerSetValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MinerSetValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return MinerSetMultiError(errors)
	}

	return nil
}

// MinerSetMultiError is an error wrapping multiple validation errors returned
// by MinerSet.ValidateAll() if the designated constraints aren't met.
type MinerSetMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MinerSetMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MinerSetMultiError) AllErrors() []error { return m }

// MinerSetValidationError is the validation error returned by
// MinerSet.Validate if the designated constraints aren't met.
type MinerSetValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MinerSetValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MinerSetValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MinerSetValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MinerSetValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MinerSetValidationError) ErrorName() string { return "MinerSetValidationError" }

// Error satisfies the builtin error interface
func (e MinerSetValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMinerSet.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MinerSetValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MinerSetValidationError{}

// Validate checks the field values on MinerTemplate with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MinerTemplate) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MinerTemplate with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MinerTemplateMultiError, or
// nil if none found.
func (m *MinerTemplate) ValidateAll() error {
	return m.validate(true)
}

func (m *MinerTemplate) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MinerType

	// no validation rules for ChainName

	// no validation rules for DataDir

	if len(errors) > 0 {
		return MinerTemplateMultiError(errors)
	}

	return nil
}

// MinerTemplateMultiError is an error wrapping multiple validation errors
// returned by MinerTemplate.ValidateAll() if the designated constraints
// aren't met.
type MinerTemplateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MinerTemplateMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MinerTemplateMultiError) AllErrors() []error { return m }

// MinerTemplateValidationError is the validation error returned by
// MinerTemplate.Validate if the designated constraints aren't met.
type MinerTemplateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MinerTemplateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MinerTemplateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MinerTemplateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MinerTemplateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MinerTemplateValidationError) ErrorName() string { return "MinerTemplateValidationError" }

// Error satisfies the builtin error interface
func (e MinerTemplateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMinerTemplate.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MinerTemplateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MinerTemplateValidationError{}

// Validate checks the field values on CreateMinerSetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateMinerSetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateMinerSetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateMinerSetRequestMultiError, or nil if none found.
func (m *CreateMinerSetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateMinerSetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Replicas

	// no validation rules for DisplayName

	// no validation rules for DeletePolicy

	if all {
		switch v := interface{}(m.GetMinerTemplate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateMinerSetRequestValidationError{
					field:  "MinerTemplate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateMinerSetRequestValidationError{
					field:  "MinerTemplate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMinerTemplate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateMinerSetRequestValidationError{
				field:  "MinerTemplate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateMinerSetRequestMultiError(errors)
	}

	return nil
}

// CreateMinerSetRequestMultiError is an error wrapping multiple validation
// errors returned by CreateMinerSetRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateMinerSetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateMinerSetRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateMinerSetRequestMultiError) AllErrors() []error { return m }

// CreateMinerSetRequestValidationError is the validation error returned by
// CreateMinerSetRequest.Validate if the designated constraints aren't met.
type CreateMinerSetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateMinerSetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateMinerSetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateMinerSetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateMinerSetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateMinerSetRequestValidationError) ErrorName() string {
	return "CreateMinerSetRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateMinerSetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateMinerSetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateMinerSetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateMinerSetRequestValidationError{}

// Validate checks the field values on ListMinerSetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListMinerSetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMinerSetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListMinerSetRequestMultiError, or nil if none found.
func (m *ListMinerSetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMinerSetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Limit

	// no validation rules for Offset

	if len(errors) > 0 {
		return ListMinerSetRequestMultiError(errors)
	}

	return nil
}

// ListMinerSetRequestMultiError is an error wrapping multiple validation
// errors returned by ListMinerSetRequest.ValidateAll() if the designated
// constraints aren't met.
type ListMinerSetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMinerSetRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMinerSetRequestMultiError) AllErrors() []error { return m }

// ListMinerSetRequestValidationError is the validation error returned by
// ListMinerSetRequest.Validate if the designated constraints aren't met.
type ListMinerSetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMinerSetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMinerSetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMinerSetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMinerSetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMinerSetRequestValidationError) ErrorName() string {
	return "ListMinerSetRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListMinerSetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMinerSetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMinerSetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMinerSetRequestValidationError{}

// Validate checks the field values on ListMinerSetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListMinerSetResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMinerSetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListMinerSetResponseMultiError, or nil if none found.
func (m *ListMinerSetResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMinerSetResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TotalCount

	for idx, item := range m.GetMinerSets() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListMinerSetResponseValidationError{
						field:  fmt.Sprintf("MinerSets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListMinerSetResponseValidationError{
						field:  fmt.Sprintf("MinerSets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListMinerSetResponseValidationError{
					field:  fmt.Sprintf("MinerSets[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListMinerSetResponseMultiError(errors)
	}

	return nil
}

// ListMinerSetResponseMultiError is an error wrapping multiple validation
// errors returned by ListMinerSetResponse.ValidateAll() if the designated
// constraints aren't met.
type ListMinerSetResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMinerSetResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMinerSetResponseMultiError) AllErrors() []error { return m }

// ListMinerSetResponseValidationError is the validation error returned by
// ListMinerSetResponse.Validate if the designated constraints aren't met.
type ListMinerSetResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMinerSetResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMinerSetResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMinerSetResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMinerSetResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMinerSetResponseValidationError) ErrorName() string {
	return "ListMinerSetResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListMinerSetResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMinerSetResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMinerSetResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMinerSetResponseValidationError{}

// Validate checks the field values on GetMinerSetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetMinerSetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMinerSetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMinerSetRequestMultiError, or nil if none found.
func (m *GetMinerSetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMinerSetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return GetMinerSetRequestMultiError(errors)
	}

	return nil
}

// GetMinerSetRequestMultiError is an error wrapping multiple validation errors
// returned by GetMinerSetRequest.ValidateAll() if the designated constraints
// aren't met.
type GetMinerSetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMinerSetRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMinerSetRequestMultiError) AllErrors() []error { return m }

// GetMinerSetRequestValidationError is the validation error returned by
// GetMinerSetRequest.Validate if the designated constraints aren't met.
type GetMinerSetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMinerSetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMinerSetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMinerSetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMinerSetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMinerSetRequestValidationError) ErrorName() string {
	return "GetMinerSetRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetMinerSetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMinerSetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMinerSetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMinerSetRequestValidationError{}

// Validate checks the field values on UpdateMinerSetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateMinerSetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateMinerSetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateMinerSetRequestMultiError, or nil if none found.
func (m *UpdateMinerSetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateMinerSetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if m.DisplayName != nil {
		// no validation rules for DisplayName
	}

	if m.DeletePolicy != nil {
		// no validation rules for DeletePolicy
	}

	if len(errors) > 0 {
		return UpdateMinerSetRequestMultiError(errors)
	}

	return nil
}

// UpdateMinerSetRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateMinerSetRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateMinerSetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateMinerSetRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateMinerSetRequestMultiError) AllErrors() []error { return m }

// UpdateMinerSetRequestValidationError is the validation error returned by
// UpdateMinerSetRequest.Validate if the designated constraints aren't met.
type UpdateMinerSetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateMinerSetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateMinerSetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateMinerSetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateMinerSetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateMinerSetRequestValidationError) ErrorName() string {
	return "UpdateMinerSetRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateMinerSetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateMinerSetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateMinerSetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateMinerSetRequestValidationError{}

// Validate checks the field values on DeleteMinerSetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteMinerSetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteMinerSetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteMinerSetRequestMultiError, or nil if none found.
func (m *DeleteMinerSetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteMinerSetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return DeleteMinerSetRequestMultiError(errors)
	}

	return nil
}

// DeleteMinerSetRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteMinerSetRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteMinerSetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteMinerSetRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteMinerSetRequestMultiError) AllErrors() []error { return m }

// DeleteMinerSetRequestValidationError is the validation error returned by
// DeleteMinerSetRequest.Validate if the designated constraints aren't met.
type DeleteMinerSetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteMinerSetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteMinerSetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteMinerSetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteMinerSetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteMinerSetRequestValidationError) ErrorName() string {
	return "DeleteMinerSetRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteMinerSetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteMinerSetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteMinerSetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteMinerSetRequestValidationError{}

// Validate checks the field values on ScaleMinerSetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ScaleMinerSetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ScaleMinerSetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ScaleMinerSetRequestMultiError, or nil if none found.
func (m *ScaleMinerSetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ScaleMinerSetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Replicas

	if len(errors) > 0 {
		return ScaleMinerSetRequestMultiError(errors)
	}

	return nil
}

// ScaleMinerSetRequestMultiError is an error wrapping multiple validation
// errors returned by ScaleMinerSetRequest.ValidateAll() if the designated
// constraints aren't met.
type ScaleMinerSetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ScaleMinerSetRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ScaleMinerSetRequestMultiError) AllErrors() []error { return m }

// ScaleMinerSetRequestValidationError is the validation error returned by
// ScaleMinerSetRequest.Validate if the designated constraints aren't met.
type ScaleMinerSetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ScaleMinerSetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ScaleMinerSetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ScaleMinerSetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ScaleMinerSetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ScaleMinerSetRequestValidationError) ErrorName() string {
	return "ScaleMinerSetRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ScaleMinerSetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sScaleMinerSetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ScaleMinerSetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ScaleMinerSetRequestValidationError{}

// Validate checks the field values on Miner with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Miner) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Miner with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in MinerMultiError, or nil if none found.
func (m *Miner) ValidateAll() error {
	return m.validate(true)
}

func (m *Miner) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for DisplayName

	// no validation rules for MinerType

	// no validation rules for ChainName

	// no validation rules for DataDir

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MinerValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MinerValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MinerValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MinerValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MinerValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MinerValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return MinerMultiError(errors)
	}

	return nil
}

// MinerMultiError is an error wrapping multiple validation errors returned by
// Miner.ValidateAll() if the designated constraints aren't met.
type MinerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MinerMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MinerMultiError) AllErrors() []error { return m }

// MinerValidationError is the validation error returned by Miner.Validate if
// the designated constraints aren't met.
type MinerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MinerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MinerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MinerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MinerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MinerValidationError) ErrorName() string { return "MinerValidationError" }

// Error satisfies the builtin error interface
func (e MinerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMiner.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MinerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MinerValidationError{}

// Validate checks the field values on CreateMinerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateMinerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateMinerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateMinerRequestMultiError, or nil if none found.
func (m *CreateMinerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateMinerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DisplayName

	// no validation rules for MinerType

	// no validation rules for ChainName

	// no validation rules for DataDir

	if len(errors) > 0 {
		return CreateMinerRequestMultiError(errors)
	}

	return nil
}

// CreateMinerRequestMultiError is an error wrapping multiple validation errors
// returned by CreateMinerRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateMinerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateMinerRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateMinerRequestMultiError) AllErrors() []error { return m }

// CreateMinerRequestValidationError is the validation error returned by
// CreateMinerRequest.Validate if the designated constraints aren't met.
type CreateMinerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateMinerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateMinerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateMinerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateMinerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateMinerRequestValidationError) ErrorName() string {
	return "CreateMinerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateMinerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateMinerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateMinerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateMinerRequestValidationError{}

// Validate checks the field values on ListMinerRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListMinerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMinerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListMinerRequestMultiError, or nil if none found.
func (m *ListMinerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMinerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Limit

	// no validation rules for Offset

	if len(errors) > 0 {
		return ListMinerRequestMultiError(errors)
	}

	return nil
}

// ListMinerRequestMultiError is an error wrapping multiple validation errors
// returned by ListMinerRequest.ValidateAll() if the designated constraints
// aren't met.
type ListMinerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMinerRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMinerRequestMultiError) AllErrors() []error { return m }

// ListMinerRequestValidationError is the validation error returned by
// ListMinerRequest.Validate if the designated constraints aren't met.
type ListMinerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMinerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMinerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMinerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMinerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMinerRequestValidationError) ErrorName() string { return "ListMinerRequestValidationError" }

// Error satisfies the builtin error interface
func (e ListMinerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMinerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMinerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMinerRequestValidationError{}

// Validate checks the field values on ListMinerResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListMinerResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMinerResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListMinerResponseMultiError, or nil if none found.
func (m *ListMinerResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMinerResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TotalCount

	for idx, item := range m.GetMiners() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListMinerResponseValidationError{
						field:  fmt.Sprintf("Miners[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListMinerResponseValidationError{
						field:  fmt.Sprintf("Miners[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListMinerResponseValidationError{
					field:  fmt.Sprintf("Miners[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListMinerResponseMultiError(errors)
	}

	return nil
}

// ListMinerResponseMultiError is an error wrapping multiple validation errors
// returned by ListMinerResponse.ValidateAll() if the designated constraints
// aren't met.
type ListMinerResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMinerResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMinerResponseMultiError) AllErrors() []error { return m }

// ListMinerResponseValidationError is the validation error returned by
// ListMinerResponse.Validate if the designated constraints aren't met.
type ListMinerResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMinerResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMinerResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMinerResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMinerResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMinerResponseValidationError) ErrorName() string {
	return "ListMinerResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListMinerResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMinerResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMinerResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMinerResponseValidationError{}

// Validate checks the field values on GetMinerRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetMinerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMinerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMinerRequestMultiError, or nil if none found.
func (m *GetMinerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMinerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return GetMinerRequestMultiError(errors)
	}

	return nil
}

// GetMinerRequestMultiError is an error wrapping multiple validation errors
// returned by GetMinerRequest.ValidateAll() if the designated constraints
// aren't met.
type GetMinerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMinerRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMinerRequestMultiError) AllErrors() []error { return m }

// GetMinerRequestValidationError is the validation error returned by
// GetMinerRequest.Validate if the designated constraints aren't met.
type GetMinerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMinerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMinerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMinerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMinerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMinerRequestValidationError) ErrorName() string { return "GetMinerRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetMinerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMinerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMinerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMinerRequestValidationError{}

// Validate checks the field values on UpdateMinerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateMinerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateMinerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateMinerRequestMultiError, or nil if none found.
func (m *UpdateMinerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateMinerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if m.DisplayName != nil {
		// no validation rules for DisplayName
	}

	if m.DeletePolicy != nil {
		// no validation rules for DeletePolicy
	}

	if len(errors) > 0 {
		return UpdateMinerRequestMultiError(errors)
	}

	return nil
}

// UpdateMinerRequestMultiError is an error wrapping multiple validation errors
// returned by UpdateMinerRequest.ValidateAll() if the designated constraints
// aren't met.
type UpdateMinerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateMinerRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateMinerRequestMultiError) AllErrors() []error { return m }

// UpdateMinerRequestValidationError is the validation error returned by
// UpdateMinerRequest.Validate if the designated constraints aren't met.
type UpdateMinerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateMinerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateMinerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateMinerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateMinerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateMinerRequestValidationError) ErrorName() string {
	return "UpdateMinerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateMinerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateMinerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateMinerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateMinerRequestValidationError{}

// Validate checks the field values on DeleteMinerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteMinerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteMinerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteMinerRequestMultiError, or nil if none found.
func (m *DeleteMinerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteMinerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return DeleteMinerRequestMultiError(errors)
	}

	return nil
}

// DeleteMinerRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteMinerRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteMinerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteMinerRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteMinerRequestMultiError) AllErrors() []error { return m }

// DeleteMinerRequestValidationError is the validation error returned by
// DeleteMinerRequest.Validate if the designated constraints aren't met.
type DeleteMinerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteMinerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteMinerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteMinerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteMinerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteMinerRequestValidationError) ErrorName() string {
	return "DeleteMinerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteMinerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteMinerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteMinerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteMinerRequestValidationError{}
