// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWalleEvaluateTask = "walle_evaluate_task"

// WalleEvaluateTask mapped from table <walle_evaluate_task>
type WalleEvaluateTask struct {
	EvaluateID   int64     `gorm:"column:evaluate_id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:模型评估任务 ID" json:"evaluate_id"`
	ModelID      int64     `gorm:"column:model_id;type:bigint;not null;index:idx_model_id,priority:1;comment:模型 ID" json:"model_id"`
	ArthurID     int64     `gorm:"column:arthur_id;type:bigint;not null;comment:Arthur任务 ID" json:"arthur_id"`
	SampleID     int64     `gorm:"column:sample_id;type:bigint;not null;comment:样本 ID" json:"sample_id"`
	CompareID    int64     `gorm:"column:compare_id;type:bigint;not null;index:idx_compare_id,priority:1;comment:模型对比任务 ID，注意：非对比任务 compare_id 必须为 0" json:"compare_id"`
	Status       string    `gorm:"column:status;type:varchar(32);not null;comment:评估任务状态" json:"status"`
	ModelAddress *string   `gorm:"column:model_address;type:longtext;comment:模型的地址" json:"model_address"`
	StartedAt    time.Time `gorm:"column:started_at;type:datetime;not null;default:1970-01-01 08:00:00;comment:训练任务开始时间" json:"started_at"`
	EndedAt      time.Time `gorm:"column:ended_at;type:datetime;not null;default:1970-01-01 08:00:00;comment:训练任务结束时间" json:"ended_at"`
	CreateTime   time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`
	UpdateTime   time.Time `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"`
	Creator      string    `gorm:"column:creator;type:varchar(512);not null;comment:创建人" json:"creator"`
}

// TableName WalleEvaluateTask's table name
func (*WalleEvaluateTask) TableName() string {
	return TableNameWalleEvaluateTask
}
