#!/usr/bin/env bash

# Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/superproj/onex.
#


# Contains swagger related util functions.
#
set -o errexit
set -o nounset
set -o pipefail

# Generates types_swagger_doc_generated file for the given group version.
# $1: Name of the group version
# $2: Path to the directory where types.go for that group version exists. This
# is the directory where the file will be generated.
onex::swagger::gen_types_swagger_doc() {
  local group_version=$1
  local gv_dir=$2
  local TMPFILE
  TMPFILE="${TMPDIR:-/tmp}/types_swagger_doc_generated.$(date +%s).go"

  echo "Generating swagger type docs for ${group_version} at ${gv_dir}"

  {
    echo -e "$(cat ${ONEX_ROOT}/scripts/boilerplate.go.txt)\n"
    echo "package ${group_version##*/}"
    cat <<EOF

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using scripts/update-generated-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE. DO NOT EDIT.
EOF
  } > "${TMPFILE}"

  if ! which genswaggertypedocs >/dev/null; then
    # build if needed
    go install k8s.io/kubernetes/cmd/genswaggertypedocs
  fi

  for types in $(find ${gv_dir} -regex "/\(.*_\)types.go$")
  do
    genswaggertypedocs -s ${types} -f - >>  "${TMPFILE}"
  done

  echo "// AUTO-GENERATED FUNCTIONS END HERE" >> "${TMPFILE}"

  gofmt -w -s "${TMPFILE}"
  mv "${TMPFILE}" "${gv_dir}/types_swagger_doc_generated.go"
}
