apiVersion: v1
kind: Pod
metadata:
  name: nettool
  labels:
    app: nettool
spec:
  restartPolicy: Always
  containers:
    - name: nettool
      image: praqma/network-multitool:latest   # í ½í±ˆ å†…ç½® curlã€wgetã€telnetã€pingã€dig ç­‰
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "sleep infinity"]
      securityContext:
        runAsUser: 0
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
