// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package gateway

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/superproj/onex/internal/gateway/biz"
	"github.com/superproj/onex/internal/gateway/server"
	"github.com/superproj/onex/internal/gateway/service"
	"github.com/superproj/onex/internal/gateway/store"
	"github.com/superproj/onex/internal/pkg/bootstrap"
	"github.com/superproj/onex/pkg/db"
	"github.com/superproj/onex/pkg/generated/clientset/versioned"
	"github.com/superproj/onex/pkg/options"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(arg <-chan struct{}, appInfo bootstrap.AppInfo, config *server.Config, versionedInterface versioned.Interface, mySQLOptions *db.MySQLOptions, redisOptions *db.RedisOptions, optionsRedisOptions *options.RedisOptions, etcdOptions *options.EtcdOptions) (*kratos.App, func(), error) {
	logger := bootstrap.NewLogger(appInfo)
	registrar := bootstrap.NewEtcdRegistrar(etcdOptions)
	appConfig := bootstrap.AppConfig{
		Info:      appInfo,
		Logger:    logger,
		Registrar: registrar,
	}
	gormDB, err := db.NewMySQL(mySQLOptions)
	if err != nil {
		return nil, nil, err
	}
	datastore := store.NewStore(gormDB)
	sharedInformerFactory, err := createInformers(arg, versionedInterface)
	if err != nil {
		return nil, nil, err
	}
	bizBiz := biz.NewBiz(datastore, versionedInterface, sharedInformerFactory)
	gatewayService := service.NewGatewayService(bizBiz)
	v := server.NewMiddlewares()
	httpServer := server.NewHTTPServer(config, gatewayService, v)
	grpcServer := server.NewGRPCServer(config, gatewayService, v)
	v2 := server.NewServers(httpServer, grpcServer)
	app := bootstrap.NewApp(appConfig, v2...)
	return app, func() {
	}, nil
}
