//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/superproj/onex.

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	config "github.com/superproj/onex/internal/controller/apis/config"
	configv1beta1 "github.com/superproj/onex/pkg/config/v1beta1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ChainControllerConfiguration)(nil), (*config.ChainControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ChainControllerConfiguration_To_config_ChainControllerConfiguration(a.(*ChainControllerConfiguration), b.(*config.ChainControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ChainControllerConfiguration)(nil), (*ChainControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ChainControllerConfiguration_To_v1beta1_ChainControllerConfiguration(a.(*config.ChainControllerConfiguration), b.(*ChainControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OneXControllerManagerConfiguration)(nil), (*config.OneXControllerManagerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OneXControllerManagerConfiguration_To_config_OneXControllerManagerConfiguration(a.(*OneXControllerManagerConfiguration), b.(*config.OneXControllerManagerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.OneXControllerManagerConfiguration)(nil), (*OneXControllerManagerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_OneXControllerManagerConfiguration_To_v1beta1_OneXControllerManagerConfiguration(a.(*config.OneXControllerManagerConfiguration), b.(*OneXControllerManagerConfiguration), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_ChainControllerConfiguration_To_config_ChainControllerConfiguration(in *ChainControllerConfiguration, out *config.ChainControllerConfiguration, s conversion.Scope) error {
	out.Image = in.Image
	return nil
}

// Convert_v1beta1_ChainControllerConfiguration_To_config_ChainControllerConfiguration is an autogenerated conversion function.
func Convert_v1beta1_ChainControllerConfiguration_To_config_ChainControllerConfiguration(in *ChainControllerConfiguration, out *config.ChainControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta1_ChainControllerConfiguration_To_config_ChainControllerConfiguration(in, out, s)
}

func autoConvert_config_ChainControllerConfiguration_To_v1beta1_ChainControllerConfiguration(in *config.ChainControllerConfiguration, out *ChainControllerConfiguration, s conversion.Scope) error {
	out.Image = in.Image
	return nil
}

// Convert_config_ChainControllerConfiguration_To_v1beta1_ChainControllerConfiguration is an autogenerated conversion function.
func Convert_config_ChainControllerConfiguration_To_v1beta1_ChainControllerConfiguration(in *config.ChainControllerConfiguration, out *ChainControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ChainControllerConfiguration_To_v1beta1_ChainControllerConfiguration(in, out, s)
}

func autoConvert_v1beta1_OneXControllerManagerConfiguration_To_config_OneXControllerManagerConfiguration(in *OneXControllerManagerConfiguration, out *config.OneXControllerManagerConfiguration, s conversion.Scope) error {
	if err := configv1beta1.Convert_v1beta1_MySQLConfiguration_To_config_MySQLConfiguration(&in.MySQL, &out.MySQL, s); err != nil {
		return err
	}
	if err := configv1beta1.Convert_v1beta1_GenericControllerManagerConfiguration_To_config_GenericControllerManagerConfiguration(&in.Generic, &out.Generic, s); err != nil {
		return err
	}
	if err := configv1beta1.Convert_v1beta1_GarbageCollectorControllerConfiguration_To_config_GarbageCollectorControllerConfiguration(&in.GarbageCollectorController, &out.GarbageCollectorController, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_ChainControllerConfiguration_To_config_ChainControllerConfiguration(&in.ChainController, &out.ChainController, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_OneXControllerManagerConfiguration_To_config_OneXControllerManagerConfiguration is an autogenerated conversion function.
func Convert_v1beta1_OneXControllerManagerConfiguration_To_config_OneXControllerManagerConfiguration(in *OneXControllerManagerConfiguration, out *config.OneXControllerManagerConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta1_OneXControllerManagerConfiguration_To_config_OneXControllerManagerConfiguration(in, out, s)
}

func autoConvert_config_OneXControllerManagerConfiguration_To_v1beta1_OneXControllerManagerConfiguration(in *config.OneXControllerManagerConfiguration, out *OneXControllerManagerConfiguration, s conversion.Scope) error {
	if err := configv1beta1.Convert_config_MySQLConfiguration_To_v1beta1_MySQLConfiguration(&in.MySQL, &out.MySQL, s); err != nil {
		return err
	}
	if err := configv1beta1.Convert_config_GenericControllerManagerConfiguration_To_v1beta1_GenericControllerManagerConfiguration(&in.Generic, &out.Generic, s); err != nil {
		return err
	}
	if err := configv1beta1.Convert_config_GarbageCollectorControllerConfiguration_To_v1beta1_GarbageCollectorControllerConfiguration(&in.GarbageCollectorController, &out.GarbageCollectorController, s); err != nil {
		return err
	}
	if err := Convert_config_ChainControllerConfiguration_To_v1beta1_ChainControllerConfiguration(&in.ChainController, &out.ChainController, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_OneXControllerManagerConfiguration_To_v1beta1_OneXControllerManagerConfiguration is an autogenerated conversion function.
func Convert_config_OneXControllerManagerConfiguration_To_v1beta1_OneXControllerManagerConfiguration(in *config.OneXControllerManagerConfiguration, out *OneXControllerManagerConfiguration, s conversion.Scope) error {
	return autoConvert_config_OneXControllerManagerConfiguration_To_v1beta1_OneXControllerManagerConfiguration(in, out, s)
}
