// Copyright 2024 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/superproj/onex.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/superproj/onex/internal/gateway/biz (interfaces: IBiz)

// Package biz is a generated GoMock package.
package biz

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	miner "github.com/superproj/onex/internal/gateway/biz/miner"
	minerset "github.com/superproj/onex/internal/gateway/biz/minerset"
)

// MockIBiz is a mock of IBiz interface.
type MockIBiz struct {
	ctrl     *gomock.Controller
	recorder *MockIBizMockRecorder
}

// MockIBizMockRecorder is the mock recorder for MockIBiz.
type MockIBizMockRecorder struct {
	mock *MockIBiz
}

// NewMockIBiz creates a new mock instance.
func NewMockIBiz(ctrl *gomock.Controller) *MockIBiz {
	mock := &MockIBiz{ctrl: ctrl}
	mock.recorder = &MockIBizMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBiz) EXPECT() *MockIBizMockRecorder {
	return m.recorder
}

// MinerSets mocks base method.
func (m *MockIBiz) MinerSets() minerset.MinerSetBiz {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MinerSets")
	ret0, _ := ret[0].(minerset.MinerSetBiz)
	return ret0
}

// MinerSets indicates an expected call of MinerSets.
func (mr *MockIBizMockRecorder) MinerSets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MinerSets", reflect.TypeOf((*MockIBiz)(nil).MinerSets))
}

// Miners mocks base method.
func (m *MockIBiz) Miners() miner.MinerBiz {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Miners")
	ret0, _ := ret[0].(miner.MinerBiz)
	return ret0
}

// Miners indicates an expected call of Miners.
func (mr *MockIBizMockRecorder) Miners() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Miners", reflect.TypeOf((*MockIBiz)(nil).Miners))
}
